#!/usr/bin/env python3
"""
Generate printable WiFi voucher PDFs from one or more .xlsx exports.

Default output:
- Legal size landscape PDF
- 4 columns x 8 rows per page
- Each voucher: logo | code (two columns), period/devices line, footer
- No voucher is split between pages

Usage:
  python generate_vouchers_pdf.py --input-dir input --output-dir output

Examples:
  python generate_vouchers_pdf.py --input-dir input --output-dir output
  python generate_vouchers_pdf.py --input-dir input --output-dir output --rows 7
  python generate_vouchers_pdf.py --input-dir input --output-dir output --unused-only
"""

from __future__ import annotations

import argparse
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from openpyxl import load_workbook
from reportlab.lib import colors
from reportlab.lib.pagesizes import legal, landscape, portrait
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader


@dataclass(frozen=True)
class Voucher:
    code: str
    period: str = ""
    devices: str = ""
    source_file: str = ""
    row_number: int = 0


HEADER_ALIASES = {
    "code": [
        "voucher code",
        "voucher",
        "code",
        "password",
        "pin",
        "access code",
        "wifi code",
    ],
    "period": [
        "period",
        "duration",
        "validity",
        "time limit",
        "time",
        "hours",
    ],
    "devices": [
        "concurrent devices",
        "devices",
        "device limit",
        "device count",
        "max devices",
    ],
    "status": ["status", "state"],
}


def normalize_header(value: object) -> str:
    value = str(value or "").strip().lower()
    value = value.replace("_", " ").replace("-", " ")
    return re.sub(r"\s+", " ", value)


def clean_cell(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value).strip()


def find_column(headers: list[object], field: str) -> Optional[int]:
    normalized = [normalize_header(header) for header in headers]
    aliases = HEADER_ALIASES[field]

    for alias in aliases:
        if alias in normalized:
            return normalized.index(alias)

    for index, header in enumerate(normalized):
        if any(alias in header for alias in aliases):
            return index

    return None


def format_devices(devices: str) -> str:
    # Ruijie may export concurrent devices as "0/2". For printing, the limit is the useful part.
    if "/" in devices:
        limit = devices.split("/")[-1].strip()
        if limit:
            return limit
    return devices


FOOTER_ATTRIBUTION = "Generated by dumadine.com"


def format_period_display(period: str) -> str:
    """Fix exports that glue number + unit ('1Hour') and normalize casing for display."""
    s = (period or "").strip()
    if not s:
        return s
    # Ruijie often exports '1Hour', '24Hr' with no space — split number run from following letters.
    s = re.sub(r"(\d+)([A-Za-z]+)", r"\1 \2", s)
    for pat, repl in (
        (re.compile(r"\bHour\b"), "hour"),
        (re.compile(r"\bHours\b"), "hours"),
        (re.compile(r"\bHr\b"), "hr"),
        (re.compile(r"\bHrs\b"), "hrs"),
        (re.compile(r"\bMin\b"), "min"),
        (re.compile(r"\bMins\b"), "mins"),
        (re.compile(r"\bMinute\b"), "minute"),
        (re.compile(r"\bMinutes\b"), "minutes"),
        (re.compile(r"\bDay\b"), "day"),
        (re.compile(r"\bDays\b"), "days"),
    ):
        s = pat.sub(repl, s)
    return s


def format_period_devices_line(voucher: Voucher) -> str:
    """Single line like '1 hour - 2 devices' from spreadsheet period/device columns."""
    period = format_period_display((voucher.period or "").strip())
    devices_raw = (voucher.devices or "").strip()
    dev = format_devices(devices_raw) if devices_raw else ""
    if period and dev:
        return f"{period} - {dev} devices"
    if period:
        return period
    if dev:
        return f"{dev} devices"
    return ""


def find_header_row(rows: list[tuple[object, ...]]) -> tuple[int, list[object]]:
    """Find a likely header row within the first few rows. Falls back to the first row."""
    for index, row in enumerate(rows[:10]):
        headers = list(row)
        if find_column(headers, "code") is not None:
            return index, headers
    return 0, list(rows[0]) if rows else []


def read_vouchers_from_xlsx(path: Path, unused_only: bool = False) -> list[Voucher]:
    workbook = load_workbook(path, read_only=True, data_only=True)
    vouchers: list[Voucher] = []

    for worksheet in workbook.worksheets:
        all_rows = list(worksheet.iter_rows(values_only=True))
        if not all_rows:
            continue

        header_index, headers = find_header_row(all_rows)
        code_col = find_column(headers, "code")
        period_col = find_column(headers, "period")
        devices_col = find_column(headers, "devices")
        status_col = find_column(headers, "status")

        # Fallback for simple files that only contain voucher codes in column A.
        if code_col is None:
            code_col = 0

        for absolute_index, row in enumerate(all_rows[header_index + 1 :], start=header_index + 2):
            row_values = list(row)
            if code_col >= len(row_values):
                continue

            code = clean_cell(row_values[code_col])
            if not code or normalize_header(code) in {"voucher code", "code"}:
                continue

            if unused_only and status_col is not None and status_col < len(row_values):
                status = normalize_header(row_values[status_col])
                if status not in {"not used", "unused", "available", "new"}:
                    continue

            period = clean_cell(row_values[period_col]) if period_col is not None and period_col < len(row_values) else ""
            devices = clean_cell(row_values[devices_col]) if devices_col is not None and devices_col < len(row_values) else ""

            vouchers.append(
                Voucher(
                    code=code,
                    period=period,
                    devices=devices,
                    source_file=path.name,
                    row_number=absolute_index,
                )
            )

    workbook.close()
    return vouchers


def read_all_vouchers(input_dir: Path, unused_only: bool = False) -> list[Voucher]:
    files = sorted(
        path for path in input_dir.glob("*.xlsx")
        if path.is_file() and not path.name.startswith("~$")
    )
    if not files:
        raise FileNotFoundError(f"No .xlsx files found in {input_dir}")

    seen_codes: set[str] = set()
    vouchers: list[Voucher] = []
    duplicate_count = 0

    for file_path in files:
        for voucher in read_vouchers_from_xlsx(file_path, unused_only=unused_only):
            dedupe_key = voucher.code.lower()
            if dedupe_key in seen_codes:
                duplicate_count += 1
                continue
            seen_codes.add(dedupe_key)
            vouchers.append(voucher)

    if duplicate_count:
        print(f"Skipped duplicate voucher codes: {duplicate_count}")

    return vouchers


def draw_centered_text(
    pdf: canvas.Canvas,
    text: str,
    x: float,
    y: float,
    width: float,
    font_name: str,
    font_size: float,
) -> None:
    pdf.setFont(font_name, font_size)
    pdf.drawCentredString(x + width / 2, y, text)


def draw_logo(
    pdf: canvas.Canvas,
    logo_path: Optional[Path],
    x: float,
    y_top: float,
    width: float,
    max_height: float,
    y_band_bottom: Optional[float] = None,
) -> None:
    def fallback_baseline() -> float:
        if y_band_bottom is not None:
            return (y_top + y_band_bottom) / 2 - 4
        return y_top - 14

    if not logo_path or not logo_path.exists():
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawCentredString(x + width / 2, fallback_baseline(), "Mulat Cafe")
        return

    try:
        image = ImageReader(str(logo_path))
        image_width, image_height = image.getSize()
        target_width = min(width * 0.95, width, 1.18 * inch)
        target_height = target_width * image_height / image_width

        if target_height > max_height:
            target_height = max_height
            target_width = target_height * image_width / image_height

        if y_band_bottom is not None:
            center_y = (y_top + y_band_bottom) / 2
            bottom_y = center_y - target_height / 2
        else:
            bottom_y = y_top - target_height

        pdf.drawImage(
            image,
            x + (width - target_width) / 2,
            bottom_y,
            width=target_width,
            height=target_height,
            mask="auto",
        )
    except Exception as exc:
        print(f"Warning: could not draw logo {logo_path}: {exc}")
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawCentredString(x + width / 2, fallback_baseline(), "Mulat Cafe")


def draw_voucher(
    pdf: canvas.Canvas,
    voucher: Voucher,
    x: float,
    y: float,
    width: float,
    height: float,
    logo_path: Optional[Path],
) -> None:
    pdf.setStrokeColor(colors.HexColor("#9A9A9A"))
    pdf.setLineWidth(0.7)
    pdf.roundRect(x, y, width, height, 4, stroke=1, fill=0)

    padding = 0.06 * inch
    inner_left = x + padding
    inner_bottom = y + padding
    inner_right = x + width - padding
    inner_top = y + height - padding
    inner_w = inner_right - inner_left

    # Period/devices line (e.g. "1 hour - 2 devices"); footer is just slightly smaller.
    detail_fs = 7.5
    footer_fs = detail_fs - 0.5
    middle_text = format_period_devices_line(voucher)

    footer_band = footer_fs + 10
    main_bottom = inner_bottom + footer_band
    main_top = inner_top
    main_h = main_top - main_bottom

    col_gap = 0.045 * inch
    avail_w = inner_w - col_gap
    logo_col_w = avail_w * 0.42
    code_col_w = avail_w - logo_col_w
    logo_col_x = inner_left
    code_col_x = inner_left + logo_col_w + col_gap

    code_font_size = min(22, max(13, main_h * 0.34))

    # Helvetica-ish vertical metrics for centering the code + details stack in column 2
    code_asc = code_font_size * 0.72
    code_desc = code_font_size * 0.22
    detail_asc = detail_fs * 0.72
    detail_desc = detail_fs * 0.22
    line_gap_pt = 6.0

    if middle_text:
        block_h = code_asc + code_desc + line_gap_pt + detail_asc + detail_desc
    else:
        block_h = code_asc + code_desc

    stack_center_y = (main_bottom + main_top) / 2
    top_y = stack_center_y + block_h / 2
    bottom_y = stack_center_y - block_h / 2

    code_baseline = top_y - code_asc

    logo_max_height = max(0.12 * inch, min(main_h - 0.04 * inch, 0.52 * inch))
    draw_logo(
        pdf,
        logo_path,
        logo_col_x,
        main_top - 2,
        logo_col_w,
        logo_max_height,
        y_band_bottom=main_bottom,
    )

    draw_centered_text(pdf, voucher.code, code_col_x, code_baseline, code_col_w, "Helvetica-Bold", code_font_size)

    if middle_text:
        pdf.setFillColor(colors.HexColor("#222222"))
        details_baseline = bottom_y + detail_desc
        draw_centered_text(pdf, middle_text, code_col_x, details_baseline, code_col_w, "Helvetica", detail_fs)
        pdf.setFillColor(colors.black)

    pdf.setFillColor(colors.HexColor("#666666"))
    pdf.setFont("Helvetica", footer_fs)
    footer_baseline = inner_bottom + footer_fs * 0.35 + 2
    pdf.drawCentredString(inner_left + inner_w / 2, footer_baseline, FOOTER_ATTRIBUTION)
    pdf.setFillColor(colors.black)


def generate_pdf(
    vouchers: list[Voucher],
    output_path: Path,
    logo_path: Optional[Path],
    columns: int,
    rows: int,
    orientation: str,
) -> None:
    page_size = landscape(legal) if orientation == "landscape" else portrait(legal)
    page_width, page_height = page_size

    margin_x = 0.22 * inch
    margin_y = 0.22 * inch
    gap_x = 0.06 * inch
    gap_y = 0.06 * inch

    voucher_width = (page_width - (2 * margin_x) - ((columns - 1) * gap_x)) / columns
    voucher_height = (page_height - (2 * margin_y) - ((rows - 1) * gap_y)) / rows
    vouchers_per_page = columns * rows

    output_path.parent.mkdir(parents=True, exist_ok=True)

    pdf = canvas.Canvas(str(output_path), pagesize=page_size)
    pdf.setTitle("Mulat Cafe WiFi Vouchers")
    pdf.setAuthor("Mulat Cafe")

    for index, voucher in enumerate(vouchers):
        slot = index % vouchers_per_page
        if index > 0 and slot == 0:
            pdf.showPage()

        column = slot % columns
        row = slot // columns

        x = margin_x + column * (voucher_width + gap_x)
        y_top = page_height - margin_y - row * (voucher_height + gap_y)
        y = y_top - voucher_height

        draw_voucher(
            pdf=pdf,
            voucher=voucher,
            x=x,
            y=y,
            width=voucher_width,
            height=voucher_height,
            logo_path=logo_path,
        )

    pdf.save()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate legal-size printable WiFi voucher PDFs from .xlsx files.")
    parser.add_argument("--input-dir", default="input", help="Folder containing one or more .xlsx files.")
    parser.add_argument("--output-dir", default="output", help="Folder for generated PDFs.")
    parser.add_argument("--logo", default="assets/logo.png", help="Logo image path. PNG/JPG recommended.")
    parser.add_argument("--pdf-name", default="wifi-vouchers.pdf", help="Generated PDF filename.")
    parser.add_argument("--columns", type=int, default=4, help="Voucher columns per page.")
    parser.add_argument("--rows", type=int, default=8, help="Voucher rows per page. Use 7 for larger vouchers.")
    parser.add_argument("--orientation", choices=["landscape", "portrait"], default="landscape", help="Legal paper orientation.")
    parser.add_argument("--unused-only", action="store_true", help="Only include rows where status is Not used/Unused/Available/New.")
    return parser.parse_args()


def resolve_path(path_value: str, base_dir: Path) -> Path:
    path = Path(path_value).expanduser()
    if path.is_absolute():
        return path

    # Prefer the current working directory, but fall back to the script folder.
    # This lets the script work whether you run it from the project root or elsewhere.
    cwd_path = Path.cwd() / path
    if cwd_path.exists():
        return cwd_path

    return base_dir / path


def main() -> None:
    args = parse_args()
    base_dir = Path(__file__).resolve().parent
    input_dir = resolve_path(args.input_dir, base_dir)
    output_dir = resolve_path(args.output_dir, base_dir)
    logo_path = resolve_path(args.logo, base_dir) if args.logo else None

    if args.columns <= 0 or args.rows <= 0:
        raise ValueError("--columns and --rows must be positive numbers")

    vouchers = read_all_vouchers(input_dir=input_dir, unused_only=args.unused_only)
    if not vouchers:
        raise ValueError("No voucher codes found in the .xlsx files.")

    pdf_path = output_dir / args.pdf_name
    generate_pdf(
        vouchers=vouchers,
        output_path=pdf_path,
        logo_path=logo_path,
        columns=args.columns,
        rows=args.rows,
        orientation=args.orientation,
    )

    vouchers_per_page = args.columns * args.rows
    pages = math.ceil(len(vouchers) / vouchers_per_page)

    print(f"Vouchers: {len(vouchers)}")
    print(f"Layout: legal {args.orientation}, {args.columns} columns x {args.rows} rows = {vouchers_per_page} vouchers/page")
    print(f"Pages: {pages}")
    print(f"PDF: {pdf_path}")


if __name__ == "__main__":
    main()
